add_action( "wp", function () {
    $map = array(
            "/blog/calcul-prix-revient-pertes/" => "/blog/cout-de-revient/",
            "/blog/erp-boissons/" => "/negoce/",
            "/blog/gestion-stock-reelle/" => "/blog/maitriser-la-gestion-des-stocks/",
            "/blog/logiciel-maree-mareyeur/" => "/blog/logiciel-grossiste-alimentaire/",
            "/blog/maitriser-numeros-lot-tracabilite/" => "/blog/numeros-de-lot/",
            "/business-plan-calculer-la-marge-commerciale-et-le-taux-de-marge/" => "/blog/calcul-du-prix-moyen/",
            "/comprendre-la-tracabilite-en-agroalimentaire-methodes-et-avantages/" => "/blog/erp-tracabilite-agroalimentaire/",
            "/controle-qualite-agroalimentaire-le-guide-complet-pour-les-professionnels/" => "/blog/conformite-haccp/",
            "/demo/" => "/contact/",
            "/erp-agro-alimentaire/logiciel-gestion-des-stocks-agro-alimentaire/" => "/fonctionnalites/gestion-de-stock/",
            "/erp-agro-alimentaire/production/" => "/fonctionnalites/fabrication/",
            "/erp-agro-alimentaire/tracabilite/" => "/blog/erp-tracabilite-agroalimentaire/",
            "/erp-agroalimentaire/" => "/agroalimentaire/",
            "/erp-boissons/" => "/negoce/",
            "/erp-cloud-vs-premise/" => "/blog/erp-cloud-saas-vs-on-premise/",
            "/erp-pme/" => "/blog/erp-pme/",
            "/erp-production-optimisez-vos-processus-de-fabrication/" => "/fonctionnalites/fabrication/",
            "/erp-qualite-agroalimentaire/" => "/blog/kpi-qualite-agroalimentaire/",
            "/erp-saas/" => "/blog/erp-saas/",
            "/formation/" => "/contact/",
            "/gestion-de-comptabilite/" => "/fonctionnalites/facturation/",
            "/gestion-de-relation-client/" => "/fonctionnalites/crm/",
            "/gestion-de-stock/" => "/fonctionnalites/gestion-de-stock/",
            "/gestion-stocks/" => "/fonctionnalites/gestion-de-stock/",
            "/guide-complet-sur-les-erp-system-saas-lequel-choisir/" => "/blog/erp-saas-cloud/",
            "/les-meilleurs-erp-de-gestion-de-stock-agroalimentaire-en-2024/" => "/fonctionnalites/gestion-de-stock/",
            "/logiciel-gestion-des-stocks-agro-alimentaire/" => "/fonctionnalites/gestion-de-stock/",
            "/logiciel-inventaire-guide-complet-pour-choisir-le-meilleur-en-2024/" => "/blog/gestion-des-inventaires/",
            "/logiciel-maree-mareyeur/" => "/blog/logiciel-grossiste-alimentaire/",
            "/negoce/boissons/" => "/negoce/",
            "/quel-erp-choisir-pour-une-pme-industrielle/" => "/blog/erp-pme/",
            "/roi-calculator/" => "/blog/roi-erp/",
            "/solutions/" => "/agroalimentaire/",
        );
    $path = rtrim( strtok( $_SERVER["REQUEST_URI"], "?" ), "/" ) . "/";
    if ( isset( $map[ $path ] ) ) { wp_safe_redirect( home_url( $map[ $path ] ), 301 ); exit; }
}, 1 );